---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: octy-jobs-deploy
  namespace: octy-production
  labels:
    app: octy-jobs-app
spec:
  selector:
    matchLabels:
      app: octy-jobs-app
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: octy-jobs-app
    spec:
      containers:
      - name: octy-jobs-app
        image: benpayflic/octy-jobs-service:$COMMIT_SHA1
        imagePullPolicy: Always
        env:
          - name: POD_ID
            valueFrom: {fieldRef: {fieldPath: metadata.name}}
          - name: OCTY_JOB_CONFIG # name that can be refefenced in app
            valueFrom:
              configMapKeyRef:
                name: octy-jobs-config  # The ConfigMap this value comes from.
                key: octy_jobs_config # The key to fetch.
          - name: OCTY_JOB_SECRETS # name that can be refefenced in app
            valueFrom:
              secretKeyRef:
                name: octy-jobs-secrets # The Secret this value comes from.
                key: octy_jobs_secrets # The key to fetch.
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 180
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 180
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "300m"
      imagePullSecrets:
      - name: docker-hub-key
