apiVersion: v1
kind: Service
metadata:
  name: octy_jobs-service
  labels:
    app: octy_jobs-app
spec:
  type: ClusterIP
  selector:
    app: octy_jobs-app
  ports:
    - protocol: TCP
      name: http
      port: 1034
      targetPort: 8080
