version: 2.1

orbs:
  python: circleci/python@1.2

jobs:
  test:
    docker:
      - image: cimg/python:3.8
    # Checkout the code as the first step. This is a dedicated CircleCI step.
    # The python orb's install-packages step will install the dependencies from a Pipfile via Pipenv by default.
    # Here we're making sure we use just use the system-wide pip. By default it uses the project root's requirements.txt.
    # Then run your tests!
    # CircleCI will report the results back to your VCS provider.
    steps:
      - checkout      
      - run:
          name: Install octy-rabbitmq-lib
          command: |
            pip install git+https://$GIT_TOKEN@github.com/Octy-ai/octy-rabbitmq-lib.git@1.1.0
      - python/install-packages:
          pkg-manager: pip
          # app-dir: ~/project/package-directory/  # If you're requirements.txt isn't in the root directory.
          # pip-dependency-file: test-requirements.txt  # if you have a different name for your requirements file, maybe one that combines your runtime and test requirements.
      - run:
          name: Run tests
          # This assumes pytest is installed via the install-package step above
          command: pytest

  build-deploy:
    docker:
      - image: circleci/buildpack-deps:stretch
    environment:
        CIRCLE_COMPARE_URL: << pipeline.project.git_url >>/compare/<< pipeline.git.base_revision >>..<<pipeline.git.revision>>
    working_directory: ~/app
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install envsubst
          command: |
            sudo apt-get update && sudo apt-get -y install gettext-base
      - run:
          name: Install kubectl
          command: |
            curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
            chmod u+x ./kubectl
      - run:
          name: Install JQ
          command: | 
            sudo apt-get update && sudo apt-get install jq
      - run:
          name: Authenticate Docker
          # $CIRCLE_SHA1 is the hash of the commit
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run:
          name: Deploy Code
          command : ./scripts/ci-deploy.sh

workflows:
  version: 2
  build-master:
    jobs:
      - test:
          filters:
            branches:
              ignore: master
      - build-deploy:
          filters:
            branches:
              only: master