apiVersion: v1
kind: Service
metadata:
  name: recommendations-service
  labels:
    app: recommendations-app
spec:
  type: ClusterIP
  selector:
    app: recommendations-app
  ports:
    - protocol: TCP
      name: http
      port: 1032
      targetPort: 8080