apiVersion: v1
kind: Service
metadata:
  name: configurations-service
  namespace: octy-development
  labels:
    app: configurations-app
spec:
  type: ClusterIP
  selector:
    app: configurations-app
  ports:
    - protocol: TCP
      name: http
      port: 1026
      targetPort: 8080
