apiVersion: v1
kind: Service
metadata:
  name: admin-service
  namespace: octy-production
  labels:
    app: admin-app
spec:
  type: ClusterIP
  selector:
    app: admin-app
  ports:
    - protocol: TCP
      name: http
      port: 1025
      targetPort: 8080