---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: segmentation-worker-deploy
  namespace: octy-production
  labels:
    app: segmentation-worker-app
spec:
  selector:
    matchLabels:
      app: segmentation-worker-app
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: segmentation-worker-app
    spec:
      containers:
      - name: segmentation-worker-app
        image: benpayflic/octy-segmentation-worker:$COMMIT_SHA1
        imagePullPolicy: Always
        env:
          - name: SEGMENTATION_WORKER_CONFIG # name that can be refefenced in app
            valueFrom:
              configMapKeyRef:
                name: segmentation-worker-config  # The ConfigMap this value comes from.
                key: segmentation_worker_config # The key to fetch.
          - name: SEGMENTATION_WORKER_SECRETS # name that can be refefenced in app
            valueFrom:
              secretKeyRef:
                name: segmentation-worker-secrets # The Secret this value comes from.
                key: segmentation_worker_secrets # The key to fetch.
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "300m"
      imagePullSecrets:
      - name: docker-hub-key