---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: messaging-deploy
  labels:
    app: messaging-app
    test: test
  annotations:
    fluxcd.io/tag.messaging-app: semver:~1.0
    fluxcd.io/automated: "true"
spec:
  selector:
    matchLabels:
      app: messaging-app
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: messaging-app
    spec:
      containers:
      - name: messaging-app
        image: aimvector/python:1.0.4
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          livenessProbe:
           httpGet:
             path: /status
             port: 8080
           initialDelaySeconds: 3
           periodSeconds: 3
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "500m"
#NOTE: comment out `volumeMounts` section for configmap and\or secret guide
          volumeMounts:
          - name: secret-volume
            mountPath: /secrets/
          - name: config-volume
            mountPath: /configs/
#NOTE: comment out `volumes` section for configmap and\or secret guide
        volumes:
        - name: secret-volume
          secret:
           secretName: mongo-conn
        - name: config-volume
          configMap:
           name: messaging-config #name of our configmap object
