---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: items-deploy
  namespace: octy-production
  labels:
    app: items-app
spec:
  selector:
    matchLabels:
      app: items-app
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: items-app
    spec:
      containers:
      - name: items-app
        image: benpayflic/octy-items-service:$COMMIT_SHA1
        imagePullPolicy: Always
        env:
          - name: ITEMS_CONFIG # name that can be refefenced in app
            valueFrom:
              configMapKeyRef:
                name: items-config  # The ConfigMap this value comes from.
                key: items_config # The key to fetch.
          - name: ITEMS_SECRETS # name that can be refefenced in app
            valueFrom:
              secretKeyRef:
                name: items-secrets # The Secret this value comes from.
                key: items_secrets # The key to fetch.
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 180
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 180
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "300m"
      imagePullSecrets:
      - name: docker-hub-key
