# Datadog Agent with Datadog Cluster Agent and
# OrchestratorExplorer (Live Containers), Check Runners, and
# External Metrics Server enabled

targetSystem: "linux"
datadog:
  apiKeyExistingSecret: datadog-api-key
  appKeyExistingSecret: datadog-app-key
  clusterName: octy.production.k8.cluster
  tags: []
  orchestratorExplorer:
    enabled: true
  logs:
    enabled: true
    containerCollectAll: true
clusterAgent:
  replicas: 2
  rbac:
    create: true
    serviceAccountName: default
  metricsProvider:
    enabled: true
    createReaderRbac: true
    useDatadogMetrics: true
    service:
      type: ClusterIP
      port: 8443
agents:
  rbac:
    create: true
    serviceAccountName: default
clusterChecksRunner:
  enabled: true
  rbac:
    create: true
    serviceAccountName: default
  replicas: 2

#helm install datadog-agent -f /Users/bengoodenough/Documents/Octy/Builds/octy-services/kubernetes/production/helm/datadog/values.yaml --set datadog.site='datadoghq.eu' --set datadog.apiKey='' datadog/datadog